#!/usr/bin/env python3
"""Deterministic synthetic corpus generator.

Read ``SCHEMA.md`` next to this file first: it documents the plant model, the
schema of every output, and exactly which defects are injected and why.

Two rules govern this file:

1. **The facts are scripted, not sampled.** The plant, the failure history, the
   procedure steps and the incident narratives are written out explicitly below.
   A generator that samples its facts produces noise with no causal structure,
   and a corpus with no causal structure cannot demonstrate that the system
   found a causal structure.
2. **Only the surface forms are varied**, by a seeded PRNG. That is where the
   deliberate messiness lives -- which of six tag spellings a row uses, whether
   the failure code is the real one or the dropdown default, whether a close-out
   date was ever entered.

Same seed, byte-identical output. That is what keeps ingestion idempotent and the
golden question set valid across regeneration.

Everything written here is SYNTHETIC TEST DATA and says so in its own content.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
import sys
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path

GENERATOR_VERSION = "1.0.0"
DEFAULT_SEED = 20260101

BANNER = (
    "SYNTHETIC TEST DATA -- generated by data/synthetic/generate.py. "
    "Not a real plant, not a real incident. Must not be used as evidence."
)

# ---------------------------------------------------------------------------
# The plant. Scripted, not sampled.
# ---------------------------------------------------------------------------

SITE = "HALDIA"
PLANT = "CDU-1"
SYSTEM = "Crude Charge Pumping"
FUNCTIONAL_LOCATION = "CDU1-PUMP-101"

#: The six spellings of the same pump that appear across real systems. The
#: fourth uses U+2011 NON-BREAKING HYPHEN, which is what a Word autocorrect
#: leaves behind and which is invisible to a human reviewer.
TAG_VARIANTS_B: tuple[str, ...] = (
    "P-101B",
    "P101B",
    "P 101 B",
    "10-P-101-B",
    "P-101-B",
    "P‑101‑B",
)
TAG_VARIANTS_A: tuple[str, ...] = ("P-101A", "P101A", "10-P-101-A", "P-101-A")

#: Technician shorthand. Unparseable by grammar on purpose: it must be resolved
#: from the record's own functional location, not from the string.
SHORTHAND_B: tuple[str, ...] = ("the B pump", "std by pump", "101B pump", "standby pump")

FAILURE_CODES = ("SEAL_LEAK", "BEARING", "VIBRATION", "OTHER")

#: Fraction of corrective work orders whose coded failure mode is the dropdown
#: default rather than the real one. Documented, not accidental: it is what makes
#: "we re-coded them from the technician's own words" measurable.
MISCODED_FRACTION = 0.45


@dataclass(frozen=True)
class WorkOrderFact:
    """One scripted maintenance event."""

    wo_id: str
    asset: str  # "B" | "A" | tag string for other equipment
    order_type: str
    opened: date
    duration_days: int
    short_text: str
    long_text: str
    as_found: str
    as_left: str
    true_failure_code: str
    downtime_hrs: float | None
    cost: int | None
    priority: str = "3-NORMAL"
    use_shorthand: bool = False
    omit_close_date: bool = False


# The failure history. This is the causal spine of the whole demo: repeated seal
# failures on both pumps of a duty/standby pair, preceded by degradation
# language, with the 2023 impeller trim sitting underneath as an unreferenced
# change.
WORK_ORDER_FACTS: tuple[WorkOrderFact, ...] = (
    WorkOrderFact(
        "WO-2101",
        "B",
        "PREVENTIVE",
        date(2019, 1, 14),
        1,
        "6-monthly PM - crude charge pump standby",
        "Routine PM carried out. Gland slightly weeping, topped up flush fluid. "
        "Coupling alignment checked, within tolerance. Monitor closely at next PM.",
        "Gland weeping, minor",
        "Flush topped up, monitored",
        "OTHER",
        4.0,
        18000,
    ),
    WorkOrderFact(
        "WO-2140",
        "B",
        "CORRECTIVE",
        date(2019, 3, 22),
        2,
        "Mechanical seal leak on standby pump",
        "Called out after seal leakage observed during startup. Found outboard seal faces "
        "scored. Operator confirms suction valve was throttled during the start. Seal "
        "cartridge replaced. See incident report INC-2019-07.",
        "Outboard seal faces scored, evidence of dry running",
        "New seal cartridge fitted, test run satisfactory",
        "SEAL_LEAK",
        16.0,
        285000,
        priority="2-HIGH",
    ),
    WorkOrderFact(
        "WO-2233",
        "A",
        "CORRECTIVE",
        date(2019, 9, 3),
        1,
        "High vibration on duty pump",
        "Vibration increased on the duty pump. Bearing housing temperature rising. "
        "Outboard bearing replaced, alignment corrected.",
        "Outboard bearing pitted",
        "Bearing replaced, alignment corrected",
        "BEARING",
        9.0,
        142000,
    ),
    WorkOrderFact(
        "WO-2390",
        "B",
        "PREVENTIVE",
        date(2020, 2, 11),
        1,
        "6-monthly PM",
        "PM completed. Slight seepage at seal drain noted, within acceptance. "
        "Tightened gland follower. No further action this outage.",
        "Slight seepage at seal drain",
        "Gland follower tightened",
        "OTHER",
        3.5,
        16000,
    ),
    WorkOrderFact(
        "WO-2455",
        "B",
        "CORRECTIVE",
        date(2020, 7, 19),
        1,
        "Abnormal noise reported by panel operator",
        "Attended on shift. Unusual noise from the B pump on start. Temporary repair - "
        "clamp fitted to flush line. Will attend during shutdown.",
        "Flush line joint leaking",
        "Temporary clamp fitted",
        "OTHER",
        2.0,
        9000,
        use_shorthand=True,
    ),
    WorkOrderFact(
        "WO-2612",
        "A",
        "PREVENTIVE",
        date(2021, 1, 20),
        1,
        "6-monthly PM - duty pump",
        "PM completed, no abnormality. Vibration readings within limits.",
        "No abnormality",
        "As found",
        "OTHER",
        3.0,
        15000,
    ),
    WorkOrderFact(
        "WO-2744",
        "B",
        "CORRECTIVE",
        date(2021, 6, 8),
        2,
        "Seal leakage, standby pump",
        "Seal leaking again on the standby pump. Same location as 2019. Faces scored. "
        "Startup was carried out with suction throttled per the operator log. Seal replaced.",
        "Seal faces scored, dry running suspected",
        "Seal replaced, run-in satisfactory",
        "SEAL_LEAK",
        14.0,
        268000,
        priority="2-HIGH",
        use_shorthand=True,
    ),
    WorkOrderFact(
        "WO-2901",
        "B",
        "PREVENTIVE",
        date(2022, 1, 17),
        1,
        "6-monthly PM",
        "PM done. Refilled oil in bearing housing. Monitor closely.",
        "Oil level low",
        "Oil refilled",
        "OTHER",
        3.0,
        15500,
    ),
    WorkOrderFact(
        "WO-3218",
        "A",
        "CORRECTIVE",
        date(2022, 8, 4),
        3,
        "Mechanical seal failure after startup",
        "Seal failure on the duty pump after startup with suction throttled. Faces badly "
        "scored, secondary damage to sleeve. Investigated as INC-2022-19.",
        "Seal faces badly scored, sleeve damaged, dry running",
        "Seal and sleeve replaced",
        "SEAL_LEAK",
        22.0,
        410000,
        priority="1-EMERGENCY",
    ),
    WorkOrderFact(
        "WO-3355",
        "B",
        "INSPECTION",
        date(2023, 2, 9),
        1,
        "Vibration route reading",
        "Route reading taken. Overall vibration slightly elevated versus baseline. "
        "Recommend trending.",
        "Vibration slightly elevated",
        "No intervention",
        "OTHER",
        None,
        None,
        omit_close_date=True,
    ),
    WorkOrderFact(
        "WO-3502",
        "B",
        "CORRECTIVE",
        date(2023, 7, 26),
        2,
        "Impeller trim following MOC-2023-07",
        "Impeller trimmed from 330 mm to 310 mm per approved MOC-2023-07 to reduce "
        "discharge pressure. Pump re-tested. Note: datasheet not yet updated.",
        "Impeller 330 mm as built",
        "Impeller trimmed to 310 mm",
        "OTHER",
        26.0,
        520000,
        priority="2-HIGH",
    ),
    WorkOrderFact(
        "WO-3688",
        "B",
        "PREVENTIVE",
        date(2024, 1, 15),
        1,
        "6-monthly PM",
        "PM completed. Running hot on the outboard bearing compared with last route. "
        "Temperature rising trend noted. Monitor closely.",
        "Outboard bearing running hot",
        "Greased, monitored",
        "OTHER",
        3.0,
        16500,
    ),
    WorkOrderFact(
        "WO-4471",
        "B",
        "CORRECTIVE",
        date(2024, 3, 12),
        1,
        "High vibration and seal leak",
        "Attended for high vibration. Found outboard seal faces scored, evidence of dry "
        "running during startup. Operator confirms suction valve was throttled. Replaced "
        "outboard mechanical seal. Recommend suction pressure interlock - already raised "
        "as CAPA-88 in 2022.",
        "Outboard seal faces scored, evidence of dry running",
        "Outboard mechanical seal replaced",
        "SEAL_LEAK",
        14.0,
        340000,
        priority="1-EMERGENCY",
    ),
    WorkOrderFact(
        "WO-4602",
        "E-104",
        "INSPECTION",
        date(2024, 6, 4),
        1,
        "Crude preheat exchanger tube inspection",
        "Tube bundle inspected during turnaround. Wall thickness readings taken at "
        "designated CMLs. No through-wall defects.",
        "Wall loss within allowance",
        "No intervention",
        "OTHER",
        None,
        45000,
    ),
    WorkOrderFact(
        "WO-4790",
        "B",
        "PREVENTIVE",
        date(2025, 1, 20),
        1,
        "6-monthly PM",
        "PM completed. Slight leak at the seal drain observed. Deferred to shutdown.",
        "Slight leak at seal drain",
        "Deferred to shutdown",
        "OTHER",
        3.0,
        16000,
    ),
)

#: Inspection: three CMLs on the exchanger, surveyed across four years so that a
#: corrosion rate and a remaining life are computable from the readings alone.
CML_SERIES: tuple[tuple[str, str, float, float, float], ...] = (
    # (equipment, cml_id, start_thickness_mm, loss_per_year_mm, min_thickness_mm)
    ("E-104", "CML-01", 12.70, 0.18, 9.50),
    ("E-104", "CML-02", 12.70, 0.31, 9.50),
    ("E-104", "CML-03", 12.70, 0.09, 9.50),
    ("V-102", "CML-11", 14.20, 0.12, 11.00),
    ("V-102", "CML-12", 14.20, 0.22, 11.00),
    ("V-102", "CML-13", 14.20, 0.05, 11.00),
)
SURVEY_DATES: tuple[date, ...] = (
    date(2019, 5, 12),
    date(2021, 5, 18),
    date(2023, 6, 2),
    date(2025, 5, 27),
)
INSPECTORS: tuple[str, ...] = ("R.S.", "A.K.", "M.P.")


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def _tag_for(rng: random.Random, asset: str, *, allow_shorthand: bool = False) -> str:
    if asset == "B":
        if allow_shorthand:
            return rng.choice(SHORTHAND_B)
        return rng.choice(TAG_VARIANTS_B)
    if asset == "A":
        return rng.choice(TAG_VARIANTS_A)
    return asset


def _fmt_date(value: date | None, style: str) -> str:
    if value is None:
        return ""
    return value.strftime("%d/%m/%Y") if style == "dmy" else value.isoformat()


def generate_work_orders(rng: random.Random, out_dir: Path) -> Path:
    path = out_dir / "work_orders_cmms_export.csv"
    rows: list[dict[str, object]] = []

    for fact in WORK_ORDER_FACTS:
        closed = None if fact.omit_close_date else fact.opened + timedelta(days=fact.duration_days)
        # Date-format variance between "source systems": half the export uses the
        # Indian day-first convention, as a real SAP export configured for the
        # local locale would.
        style = "dmy" if rng.random() < 0.5 else "iso"

        code = fact.true_failure_code
        if fact.order_type == "CORRECTIVE" and rng.random() < MISCODED_FRACTION:
            code = "OTHER"  # the dropdown default a tired technician picks

        rows.append(
            {
                "wo_id": fact.wo_id,
                "functional_location": FUNCTIONAL_LOCATION
                if fact.asset in ("A", "B")
                else f"CDU1-{fact.asset}",
                "equipment_tag": _tag_for(rng, fact.asset, allow_shorthand=fact.use_shorthand),
                "order_type": fact.order_type,
                "status": "IN_PROGRESS" if fact.omit_close_date else "CLOSED",
                "priority": fact.priority,
                "short_text": fact.short_text,
                "long_text": fact.long_text,
                "as_found": fact.as_found,
                "as_left": fact.as_left,
                "failure_code": code,
                "opened_on": _fmt_date(fact.opened, style),
                "closed_on": _fmt_date(closed, style),
                "downtime_hrs": "" if fact.downtime_hrs is None else f"{fact.downtime_hrs:.1f}",
                "actual_cost": "" if fact.cost is None else str(fact.cost),
            }
        )

    with path.open("w", encoding="utf-8", newline="") as fh:
        fh.write(f"# {BANNER}\n")
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return path


def generate_inspections(rng: random.Random, out_dir: Path) -> Path:
    path = out_dir / "inspection_ut_readings.csv"
    rows: list[dict[str, object]] = []
    report_seq = 1

    for equipment, cml_id, start, loss_per_year, minimum in CML_SERIES:
        for survey_index, survey_date in enumerate(SURVEY_DATES):
            years = (survey_date - SURVEY_DATES[0]).days / 365.25
            thickness = round(start - loss_per_year * years, 2)
            remaining = round(thickness - minimum, 2)
            observation = (
                "General wall loss consistent with previous survey."
                if remaining > 1.0
                else "Wall loss approaching retirement limit; reduce survey interval."
            )
            rows.append(
                {
                    "report_no": f"UT-{SURVEY_DATES[survey_index].year}-{report_seq:03d}",
                    "equipment_tag": equipment,
                    "cml_id": cml_id,
                    "ndt_method": "UT",
                    "inspection_date": survey_date.isoformat(),
                    "thickness_mm": f"{thickness:.2f}",
                    "min_thickness": f"{minimum:.2f}",
                    "inspector": rng.choice(INSPECTORS),
                    "observation": observation,
                }
            )
        report_seq += 1

    with path.open("w", encoding="utf-8", newline="") as fh:
        fh.write(f"# {BANNER}\n")
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return path


INCIDENT_2019 = f"""# Incident Investigation Report INC-2019-07

> {BANNER}

Site: {SITE}   Plant: {PLANT}   System: {SYSTEM}
Equipment involved: P-101B (crude charge pump, standby)
Functional location: {FUNCTIONAL_LOCATION}
Date of event: 2019-03-22
Severity: Minor -- no injury, no release outside bund
Investigation status: CLOSED

## What happened

At 02:10 on 22 March 2019 the standby crude charge pump P-101B was started to take
over from the duty pump for a planned changeover. Within four minutes of starting,
the panel operator observed a rising seal-pot level alarm and process fluid was
seen at the outboard seal drain. The pump was stopped and the duty pump restarted.

## Immediate cause

The outboard mechanical seal failed. On strip-down the seal faces were found
scored, with a witness pattern consistent with running without liquid film.

## Root cause

The startup was carried out with the suction valve throttled. Under this
condition suction pressure at the seal chamber fell below the seal's minimum
required value and the faces ran dry during the run-up. The startup procedure in
force at the time, SOP-4412 revision 2, did not require the operator to confirm
suction pressure before starting the pump. There is no interlock preventing a
start with the suction valve throttled.

## Contributing factors

- Changeover carried out at night with reduced supervision.
- The suction valve position is not indicated at the panel.
- The seal's minimum suction pressure is stated in the OEM manual but not in the
  operating procedure.

## Corrective and preventive actions

| ID | Action | Owner | Due | Status |
|---|---|---|---|---|
| CAPA-41 | Replace outboard mechanical seal | Rotating Equipment | 2019-03-25 | CLOSED |
| CAPA-42 | Brief operators on suction valve position before changeover | Operations | 2019-04-15 | CLOSED |

## Lessons learned

Starting a centrifugal pump against a throttled suction is a dry-running risk that
the procedure does not currently guard against. The same exposure exists on the
sibling pump P-101A, which shares the suction line and the same startup procedure.
"""

INCIDENT_2022 = f"""# Incident Investigation Report INC-2022-19

> {BANNER}

Site: {SITE}   Plant: {PLANT}   System: {SYSTEM}
Equipment involved: P-101A (crude charge pump, duty)
Functional location: {FUNCTIONAL_LOCATION}
Date of event: 2022-08-04
Severity: Moderate -- 22 hours unplanned downtime, no injury
Investigation status: CLOSED

## What happened

On 4 August 2022 the duty crude charge pump P-101A was restarted following a
short unit trip. Seal leakage developed within the first ten minutes of running.
The pump was isolated and the standby pump P-101B was brought into service.
Strip-down found the seal faces badly scored and the shaft sleeve damaged.

## Immediate cause

Mechanical seal failure by face damage, with secondary damage to the sleeve.

## Root cause

Startup was performed with the suction valve throttled, causing the seal faces to
run without liquid film. This is the same mechanism recorded on the sibling pump
P-101B in incident INC-2019-07. The startup procedure had been revised to SOP-4412
revision 3 but still does not require confirmation of suction pressure before
starting, and no interlock exists.

## Analysis of recurrence

This is the second recorded dry-running seal failure on this pump pair in three
years. Both occurred during startup. Both followed a throttled suction. The two
events were investigated independently and neither investigation referenced the
other, because the reports are filed by date rather than by cause.

## Corrective and preventive actions

| ID | Action | Owner | Due | Status |
|---|---|---|---|---|
| CAPA-87 | Replace seal and shaft sleeve | Rotating Equipment | 2022-08-08 | CLOSED |
| CAPA-88 | Install suction pressure interlock preventing start below minimum seal chamber pressure on both P-101A and P-101B | Reliability Engineering | 2023-03-31 | OPEN |
| CAPA-89 | Add suction pressure confirmation step to SOP-4412 | Operations | 2022-12-31 | OPEN |

## Lessons learned

Recurring failures on a duty/standby pair are easy to miss when history is held
per equipment rather than per position. The functional location {FUNCTIONAL_LOCATION}
has now suffered three seal failures across two machines.
"""

SOP_4412 = f"""# SOP-4412 Crude Charge Pump Startup

> {BANNER}

Document: SOP-4412
Revision: 3
Effective from: 2024-03-01
Supersedes: SOP-4412 revision 2, effective 2018-06-01
Applies to: P-101A, P-101B ({FUNCTIONAL_LOCATION}), {PLANT}
Owner: Operations

## 1 Scope

This procedure covers the startup of the crude charge pumps P-101A and P-101B in
the Crude Charge Pumping system of {PLANT}.

## 2 Safety

WARNING: A valid permit to work is required before any intervention on the pump
or its auxiliaries. Lock-out / tag-out shall be applied to the motor isolator
before mechanical work.

PPE required: safety helmet, safety glasses, hearing protection, flame-retardant
coverall, safety footwear, hand gloves.

## 3 Preconditions

Precondition: Confirm the pump has a valid handover from maintenance and no open
work order restricting operation.

Precondition: Confirm the suction drum V-102 level is above the low-low trip
setpoint on LSHH-305.

Precondition: Confirm the discharge pressure controller PIC-101 is in manual with
its output at zero.

## 4 Startup sequence

4.1 Open the suction valve fully. Confirm it is fully open at the valve, not at
the panel.

4.2 Open the seal flush supply and confirm flow at the seal pot.

4.3 Vent the casing at the high-point vent until liquid appears, then close the
vent.

4.4 Confirm the bearing oil level is between the sight-glass marks.

4.5 Start the motor locally. Observe the run-up.

4.6 Confirm discharge pressure develops within 30 seconds. The discharge pressure
limit is 10 barg. Revision 2 of this procedure stated 12 barg; the limit was
reduced in revision 3.

4.7 Place PIC-101 in automatic and set the required setpoint.

4.8 Confirm the outboard seal drain is dry after five minutes of running.

## 5 Shutdown

5.1 Place PIC-101 in manual and reduce output to zero.

5.2 Stop the motor.

5.3 Close the discharge valve. Leave the suction valve open unless isolating.

## 6 Isolation for maintenance

6.1 Stop the pump per section 5.

6.2 Close the suction isolation valve and the discharge isolation valve.

6.3 Apply lock-out / tag-out to the motor isolator and to both valves.

6.4 Depressurise and drain the casing to the closed drain system.

6.5 Confirm zero energy state before releasing the equipment to maintenance.

## 7 Records

Record the startup in the shift log, including the time and the operator name.
"""

MOC_2023 = f"""# Management of Change MOC-2023-07

> {BANNER}

MOC number: MOC-2023-07
Title: Impeller trim on crude charge pump P-101B
Plant: {PLANT}   System: {SYSTEM}
Equipment affected: P-101B
Approved on: 2023-07-14
Implemented on: 2023-07-26 under work order WO-3502
Status: IMPLEMENTED

## Reason for change

Discharge pressure on P-101B was consistently above the requirement of the
downstream crude preheat exchanger E-104, requiring continuous throttling at the
discharge control valve and wasting shaft power.

## Description of change

The pump impeller was trimmed from 330 mm to 310 mm diameter.

## Consequences

The pump now operates further from its original best-efficiency point. Original
design duty and NPSH required values on the equipment datasheet no longer
describe the installed machine.

## Risk review

Reviewed by Reliability Engineering. Assessed as low risk on the basis that the
trimmed duty remains within the OEM's published operating envelope. Seal chamber
pressure at reduced head was not separately assessed.

## Documents requiring update

| Document | Required update | Status |
|---|---|---|
| Equipment datasheet P-101B | Revise rated head and impeller diameter | NOT DONE |
| P&ID CDU-1 sheet 3 | Update pump duty note | NOT DONE |
| SOP-4412 | Review discharge pressure limit | DONE in revision 3 |

## Approvals

Process Engineering, Reliability Engineering, Operations, Plant Head.
"""


def write_documents(out_dir: Path) -> list[Path]:
    documents = {
        "incident_2019_seal_failure.md": INCIDENT_2019,
        "incident_2022_seal_failure.md": INCIDENT_2022,
        "sop_4412_crude_charge_pump_startup.md": SOP_4412,
        "moc_2023_07_impeller_trim.md": MOC_2023,
    }
    written: list[Path] = []
    for name, content in documents.items():
        path = out_dir / name
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def write_manifest(out_dir: Path, files: list[Path], seed: int) -> Path:
    entries = []
    for path in sorted(files):
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        entries.append(
            {
                "filename": path.name,
                "sha256": digest,
                "byte_size": path.stat().st_size,
            }
        )
    manifest = {
        "generator": "data/synthetic/generate.py",
        "generator_version": GENERATOR_VERSION,
        "seed": seed,
        "data_class": "synthetic_test_data",
        "warning": BANNER,
        "schema": "See data/synthetic/SCHEMA.md",
        "files": entries,
    }
    path = out_dir / "MANIFEST.json"
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="data/synthetic/generated", help="output directory")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="PRNG seed")
    args = parser.parse_args(argv)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(args.seed)

    files: list[Path] = [
        generate_work_orders(rng, out_dir),
        generate_inspections(rng, out_dir),
        *write_documents(out_dir),
    ]
    manifest = write_manifest(out_dir, files, args.seed)

    print(f"Generated {len(files)} files in {out_dir} (seed={args.seed})")
    for path in sorted(files) + [manifest]:
        print(f"  {path.name:44} {path.stat().st_size:>8,} bytes")
    print("\nAll output is SYNTHETIC TEST DATA. Ingest with data_class=synthetic_test_data.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
