#!/usr/bin/env python3
"""Render the synthetic corpus into real PDF files.

The *content* is the same synthetic corpus described in ``SCHEMA.md`` — not a
real plant, and labelled as such on every page. The *files* are real PDFs, which
is the point: they exercise the actual parsing paths rather than a Markdown
shortcut.

Four artefacts, each targeting a specific path through the pipeline:

``sop_4412_rev3.pdf``
    Text-layer PDF with a ruled table. Exercises pdfplumber word geometry,
    paragraph grouping and table-structure extraction.

``inspection_ut_survey_2025.pdf``
    Text-layer PDF that is mostly a wide numeric table. Exercises the "do not
    flatten a table into prose" path, where the row-column association is the
    only thing that makes the numbers mean anything.

``incident_2019_scan.pdf``
    **Image-only PDF with no text layer.** Rendered to raster and re-embedded,
    with a slight rotation so the page is not perfectly axis-aligned. This is
    the OCR path: pdfplumber will find no text, the pipeline must route it to
    OCR, and with no OCR provider configured it must say so rather than
    silently indexing an empty document.

``pid_cdu1_sheet3.pdf``
    A schematic drawn as vector geometry with tag labels: equipment symbols,
    connecting lines, instrument bubbles and a title block. Sparse text over
    dense vector objects is the drawing signature the classifier keys on.

Deterministic: same seed, byte-identical output apart from the PDF's own
creation timestamp, which is pinned so the file hash is stable and ingestion
stays idempotent across regeneration.

Requires ``reportlab`` (a dev dependency; not needed at run time).
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
from pathlib import Path

BANNER = (
    "SYNTHETIC TEST DATA - generated by data/synthetic/generate_pdfs.py. "
    "Not a real plant, not a real incident. Must not be used as evidence."
)

#: Pinned so the PDF metadata, and therefore the file hash, is reproducible.
FIXED_TIMESTAMP = "20260101000000+00'00'"

PAGE_W, PAGE_H = 595.27, 841.89  # A4 portrait, points


def _canvas(buffer: io.BytesIO, title: str, landscape: bool = False):
    from reportlab.pdfgen import canvas as pdfcanvas

    size = (PAGE_H, PAGE_W) if landscape else (PAGE_W, PAGE_H)
    c = pdfcanvas.Canvas(buffer, pagesize=size)
    c.setTitle(title)
    c.setAuthor("Unified Asset & Operations Brain - synthetic corpus")
    c.setSubject(BANNER)
    c.setProducer("reportlab")
    # reportlab reads these for /CreationDate and /ModDate.
    c._doc.info.invariant = True  # type: ignore[attr-defined]
    return c


def _banner(c, y: float, width: float) -> None:
    c.setFont("Helvetica-Oblique", 7)
    c.setFillGray(0.35)
    c.drawString(40, y, BANNER)
    c.setFillGray(0)


# ---------------------------------------------------------------------------
# SOP - text layer with a ruled table
# ---------------------------------------------------------------------------

SOP_SECTIONS: list[tuple[str, list[str]]] = [
    (
        "1 Scope",
        [
            "This procedure covers the startup of the crude charge pumps P-101A and P-101B",
            "in the Crude Charge Pumping system of CDU-1. It applies to functional location",
            "CDU1-PUMP-101.",
        ],
    ),
    (
        "2 Safety",
        [
            "WARNING: A valid permit to work is required before any intervention on the pump",
            "or its auxiliaries. Lock-out / tag-out shall be applied to the motor isolator",
            "before mechanical work.",
            "PPE required: safety helmet, safety glasses, hearing protection, flame-retardant",
            "coverall, safety footwear, hand gloves.",
        ],
    ),
    (
        "3 Preconditions",
        [
            "Precondition: Confirm the pump has a valid handover from maintenance and no open",
            "work order restricting operation.",
            "Precondition: Confirm the suction drum V-102 level is above the low-low trip",
            "setpoint on LSHH-305.",
            "Precondition: Confirm the discharge pressure controller PIC-101 is in manual with",
            "its output at zero.",
        ],
    ),
    (
        "4 Startup sequence",
        [
            "4.1 Open the suction valve fully. Confirm it is fully open at the valve, not at",
            "the panel.",
            "4.2 Open the seal flush supply and confirm flow at the seal pot.",
            "4.3 Vent the casing at the high-point vent until liquid appears, then close the",
            "vent.",
            "4.4 Confirm the bearing oil level is between the sight-glass marks.",
            "4.5 Start the motor locally. Observe the run-up.",
            "4.6 Confirm discharge pressure develops within 30 seconds. The discharge pressure",
            "limit is 10 barg. Revision 2 of this procedure stated 12 barg; the limit was",
            "reduced in revision 3.",
            "4.7 Place PIC-101 in automatic and set the required setpoint.",
            "4.8 Confirm the outboard seal drain is dry after five minutes of running.",
        ],
    ),
    (
        "5 Shutdown",
        [
            "5.1 Place PIC-101 in manual and reduce output to zero.",
            "5.2 Stop the motor.",
            "5.3 Close the discharge valve. Leave the suction valve open unless isolating.",
        ],
    ),
    (
        "6 Isolation for maintenance",
        [
            "6.1 Stop the pump per section 5.",
            "6.2 Close the suction isolation valve and the discharge isolation valve.",
            "6.3 Apply lock-out / tag-out to the motor isolator and to both valves.",
            "6.4 Depressurise and drain the casing to the closed drain system.",
            "6.5 Confirm zero energy state before releasing the equipment to maintenance.",
        ],
    ),
]

SOP_LIMITS = [
    ["Parameter", "Limit", "Unit", "Source"],
    ["Discharge pressure", "10", "barg", "SOP-4412 rev 3"],
    ["Suction pressure minimum", "2.0", "barg", "OEM manual"],
    ["Bearing temperature alarm", "85", "degC", "PIC-101 loop"],
    ["Vibration alarm", "7.1", "mm/s", "ISO 10816"],
]


def _table(c, x: float, y: float, rows: list[list[str]], widths: list[float]) -> float:
    """Draw a ruled table. The rules matter: pdfplumber finds tables from the
    lines, so an unruled table would be read as prose."""
    row_h = 16.0
    total_w = sum(widths)
    top = y

    for row_index, row in enumerate(rows):
        cursor_x = x
        c.setFont("Helvetica-Bold" if row_index == 0 else "Helvetica", 8.5)
        for col_index, cell in enumerate(row):
            c.drawString(cursor_x + 4, y - row_h + 5, str(cell))
            cursor_x += widths[col_index]
        y -= row_h

    # Horizontal rules
    c.setLineWidth(0.5)
    for i in range(len(rows) + 1):
        line_y = top - i * row_h
        c.line(x, line_y, x + total_w, line_y)
    # Vertical rules
    cursor_x = x
    for width in [0.0, *widths]:
        cursor_x += width
        c.line(cursor_x, top, cursor_x, top - len(rows) * row_h)
    return y - 10


def build_sop(path: Path) -> None:
    buffer = io.BytesIO()
    c = _canvas(buffer, "SOP-4412 Crude Charge Pump Startup")

    y = PAGE_H - 50
    c.setFont("Helvetica-Bold", 15)
    c.drawString(40, y, "SOP-4412  Crude Charge Pump Startup")
    y -= 20
    c.setFont("Helvetica", 9)
    for line in [
        "Document: SOP-4412      Revision: 3      Effective from: 2024-03-01",
        "Supersedes: SOP-4412 revision 2, effective 2018-06-01",
        "Applies to: P-101A, P-101B (CDU1-PUMP-101), CDU-1",
        "Owner: Operations",
    ]:
        c.drawString(40, y, line)
        y -= 12
    y -= 8

    for heading, lines in SOP_SECTIONS:
        if y < 130:
            _banner(c, 28, PAGE_W)
            c.showPage()
            y = PAGE_H - 50
        c.setFont("Helvetica-Bold", 10.5)
        c.drawString(40, y, heading)
        y -= 15
        c.setFont("Helvetica", 9)
        for line in lines:
            if y < 60:
                _banner(c, 28, PAGE_W)
                c.showPage()
                y = PAGE_H - 50
                c.setFont("Helvetica", 9)
            c.drawString(40, y, line)
            y -= 11.5
        y -= 8

    if y < 180:
        _banner(c, 28, PAGE_W)
        c.showPage()
        y = PAGE_H - 50
    c.setFont("Helvetica-Bold", 10.5)
    c.drawString(40, y, "7 Operating limits")
    y -= 18
    _table(c, 40, y, SOP_LIMITS, [150, 70, 60, 140])

    _banner(c, 28, PAGE_W)
    c.showPage()
    c.save()
    path.write_bytes(buffer.getvalue())


# ---------------------------------------------------------------------------
# Inspection report - wide numeric table
# ---------------------------------------------------------------------------

CML_ROWS = [
    ["CML", "Equipment", "Method", "Date", "Thickness mm", "Min mm", "Inspector"],
    ["CML-01", "E-104", "UT", "2025-05-27", "11.62", "9.50", "R.S."],
    ["CML-02", "E-104", "UT", "2025-05-27", "10.84", "9.50", "A.K."],
    ["CML-03", "E-104", "UT", "2025-05-27", "12.16", "9.50", "R.S."],
    ["CML-11", "V-102", "UT", "2025-05-27", "13.48", "11.00", "M.P."],
    ["CML-12", "V-102", "UT", "2025-05-27", "12.87", "11.00", "A.K."],
    ["CML-13", "V-102", "UT", "2025-05-27", "13.90", "11.00", "R.S."],
]


def build_inspection(path: Path) -> None:
    buffer = io.BytesIO()
    c = _canvas(buffer, "UT-2025-004 Ultrasonic Thickness Survey")

    y = PAGE_H - 50
    c.setFont("Helvetica-Bold", 15)
    c.drawString(40, y, "ULTRASONIC THICKNESS SURVEY REPORT")
    y -= 20
    c.setFont("Helvetica", 9)
    for line in [
        "Report number: UT-2025-004        Survey date: 2025-05-27",
        "Plant: CDU-1        Equipment: E-104 crude preheat exchanger, V-102 suction drum",
        "Method: Ultrasonic thickness (UT), 5 MHz dual element probe",
    ]:
        c.drawString(40, y, line)
        y -= 12
    y -= 12

    c.setFont("Helvetica-Bold", 10.5)
    c.drawString(40, y, "Readings by condition monitoring location")
    y -= 18
    y = _table(c, 40, y, CML_ROWS, [55, 70, 50, 75, 80, 55, 60])

    y -= 10
    c.setFont("Helvetica-Bold", 10.5)
    c.drawString(40, y, "Findings")
    y -= 15
    c.setFont("Helvetica", 9)
    for line in [
        "General wall loss consistent with previous surveys. CML-02 shows the highest",
        "corrosion rate at approximately 0.31 mm/yr and should be re-surveyed at a reduced",
        "interval. No through-wall defects were found. All readings remain above the",
        "retirement limit.",
    ]:
        c.drawString(40, y, line)
        y -= 11.5

    _banner(c, 28, PAGE_W)
    c.showPage()
    c.save()
    path.write_bytes(buffer.getvalue())


# ---------------------------------------------------------------------------
# Scanned incident report - image only, no text layer
# ---------------------------------------------------------------------------

INCIDENT_LINES = [
    "INCIDENT INVESTIGATION REPORT  INC-2019-07",
    "",
    "Site: HALDIA    Plant: CDU-1    System: Crude Charge Pumping",
    "Equipment involved: P-101B (crude charge pump, standby)",
    "Functional location: CDU1-PUMP-101",
    "Date of event: 2019-03-22    Severity: Minor",
    "",
    "WHAT HAPPENED",
    "At 02:10 on 22 March 2019 the standby crude charge pump P-101B was",
    "started to take over from the duty pump for a planned changeover.",
    "Within four minutes of starting, the panel operator observed a rising",
    "seal-pot level alarm and process fluid was seen at the outboard seal",
    "drain. The pump was stopped and the duty pump restarted.",
    "",
    "IMMEDIATE CAUSE",
    "The outboard mechanical seal failed. On strip-down the seal faces were",
    "found scored, with a witness pattern consistent with running without",
    "liquid film.",
    "",
    "ROOT CAUSE",
    "The startup was carried out with the suction valve throttled. Under this",
    "condition suction pressure at the seal chamber fell below the seal's",
    "minimum required value and the faces ran dry during the run-up. The",
    "startup procedure in force at the time, SOP-4412 revision 2, did not",
    "require the operator to confirm suction pressure before starting.",
    "",
    "CORRECTIVE ACTIONS",
    "CAPA-41  Replace outboard mechanical seal        Rotating Equipment  CLOSED",
    "CAPA-42  Brief operators on suction valve check  Operations          CLOSED",
]


def build_scanned_incident(path: Path) -> None:
    """Render text to a raster image, then embed the image in a PDF.

    The result has no text layer at all, which is what a scanned document really
    is. A slight rotation keeps the page off-axis, as a real scan would be.
    """
    from PIL import Image, ImageDraw, ImageFont
    from reportlab.lib.utils import ImageReader

    # 150 DPI A4 - low enough to be a realistic scan, high enough to OCR.
    width, height = 1240, 1754
    image = Image.new("L", (width, height), color=246)  # slightly grey, like paper
    draw = ImageDraw.Draw(image)

    try:
        font = ImageFont.truetype("DejaVuSans.ttf", 22)
        bold = ImageFont.truetype("DejaVuSans-Bold.ttf", 26)
    except OSError:
        font = ImageFont.load_default(size=22)
        bold = ImageFont.load_default(size=26)

    y = 90
    for line in INCIDENT_LINES:
        if not line:
            y += 18
            continue
        is_heading = line.isupper() and len(line) < 60
        draw.text((90, y), line, fill=25, font=bold if is_heading else font)
        y += 40 if is_heading else 33

    draw.text((90, height - 70), BANNER[:96], fill=110, font=ImageFont.load_default(size=16))

    # A real scan is never perfectly square to the platen.
    image = image.rotate(-0.6, resample=Image.BICUBIC, fillcolor=246, expand=False)

    buffer = io.BytesIO()
    c = _canvas(buffer, "INC-2019-07 Incident Investigation Report (scanned)")
    c.drawImage(ImageReader(image), 0, 0, width=PAGE_W, height=PAGE_H)
    c.showPage()
    c.save()
    path.write_bytes(buffer.getvalue())


# ---------------------------------------------------------------------------
# P&ID - vector geometry with tag labels
# ---------------------------------------------------------------------------


def build_pid(path: Path) -> None:
    """A schematic in vector geometry.

    Not a substitute for a real P&ID -- symbol detection and line tracing are not
    built, and this drawing is not a benchmark for them. Its purpose is to
    exercise the *classifier*: dense vector objects with sparse text is the
    drawing signature, and this file has genuinely thousands of line segments.
    """
    buffer = io.BytesIO()
    c = _canvas(buffer, "P&ID CDU-1 Sheet 3 Crude Charge Pumping", landscape=True)
    w, h = PAGE_H, PAGE_W  # landscape

    c.setLineWidth(0.4)

    # Grid background: what makes a drawing vector-dense.
    c.setStrokeGray(0.88)
    for gx in range(30, int(w) - 20, 12):
        c.line(gx, 40, gx, h - 40)
    for gy in range(40, int(h) - 40, 12):
        c.line(30, gy, w - 20, gy)
    c.setStrokeGray(0)

    def vessel(x, y, label, service):
        c.setLineWidth(1.1)
        c.roundRect(x, y, 80, 110, 12)
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(x + 40, y - 12, label)
        c.setFont("Helvetica", 6.5)
        c.drawCentredString(x + 40, y - 21, service)
        c.setLineWidth(0.4)

    def pump(x, y, label, service):
        c.setLineWidth(1.1)
        c.circle(x, y, 17)
        c.line(x - 17, y, x - 30, y)
        c.line(x, y + 17, x, y + 30)
        # Impeller marks
        for angle in range(0, 360, 45):
            import math

            c.line(
                x,
                y,
                x + 14 * math.cos(math.radians(angle)),
                y + 14 * math.sin(math.radians(angle)),
            )
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(x, y - 30, label)
        c.setFont("Helvetica", 6.5)
        c.drawCentredString(x, y - 39, service)
        c.setLineWidth(0.4)

    def exchanger(x, y, label, service):
        c.setLineWidth(1.1)
        c.rect(x, y, 100, 60)
        for i in range(1, 6):
            c.line(x, y + i * 10, x + 100, y + i * 10)
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(x + 50, y - 12, label)
        c.setFont("Helvetica", 6.5)
        c.drawCentredString(x + 50, y - 21, service)
        c.setLineWidth(0.4)

    def instrument(x, y, tag):
        c.setLineWidth(0.9)
        c.circle(x, y, 13)
        c.line(x - 13, y, x + 13, y)
        c.setFont("Helvetica", 6.5)
        c.drawCentredString(x, y + 3, tag[:3])
        c.drawCentredString(x, y - 8, tag[3:].lstrip("-"))
        c.setLineWidth(0.4)

    def valve(x, y, tag):
        c.setLineWidth(1.0)
        c.line(x - 9, y - 8, x + 9, y + 8)
        c.line(x - 9, y + 8, x + 9, y - 8)
        c.line(x - 9, y - 8, x - 9, y + 8)
        c.line(x + 9, y - 8, x + 9, y + 8)
        c.setFont("Helvetica", 6)
        c.drawCentredString(x, y - 20, tag)
        c.setLineWidth(0.4)

    def pipe(points, label=None):
        c.setLineWidth(1.4)
        for (x1, y1), (x2, y2) in zip(points, points[1:], strict=False):
            c.line(x1, y1, x2, y2)
        if label:
            mx = (points[0][0] + points[-1][0]) / 2
            my = (points[0][1] + points[-1][1]) / 2
            c.setFont("Helvetica", 6)
            c.drawString(mx - 30, my + 5, label)
        c.setLineWidth(0.4)

    vessel(80, 300, "V-102", "SUCTION DRUM")
    pump(280, 250, "P-101A", "CRUDE CHARGE (DUTY)")
    pump(280, 150, "P-101B", "CRUDE CHARGE (STANDBY)")
    exchanger(480, 250, "E-104", "CRUDE PREHEAT")
    vessel(680, 240, "T-101", "CRUDE COLUMN")

    pipe([(160, 340), (220, 340), (220, 250), (250, 250)], '8"-P-1501-A1A')
    pipe([(220, 340), (220, 150), (250, 150)])
    pipe([(280, 280), (280, 330), (440, 330), (440, 280), (480, 280)], '6"-P-1502-A1A')
    pipe([(280, 180), (400, 180), (400, 330)])
    pipe([(580, 280), (640, 280), (640, 300), (680, 300)], '6"-P-1503-A1A')

    valve(220, 250, "HV-1501")
    valve(220, 150, "HV-1502")
    valve(440, 330, "HV-1503")
    instrument(340, 330, "PIC-101")
    instrument(160, 380, "LSHH-305")
    instrument(520, 200, "FT-201")
    instrument(600, 340, "PSV-204")

    # Title block, bottom right - the reliable drawing signal.
    c.setLineWidth(1.0)
    c.rect(w - 300, 45, 270, 90)
    c.line(w - 300, 105, w - 30, 105)
    c.line(w - 300, 75, w - 30, 75)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(w - 293, 113, "PIPING AND INSTRUMENTATION DIAGRAM")
    c.setFont("Helvetica", 7)
    c.drawString(w - 293, 85, "CDU-1  CRUDE CHARGE PUMPING")
    c.drawString(w - 293, 55, "DWG No: PID-CDU1-003      REV: 4      DATE: 2018-11-12")

    c.setFont("Helvetica-Oblique", 6)
    c.setFillGray(0.4)
    c.drawString(30, 30, BANNER)

    c.showPage()
    c.save()
    path.write_bytes(buffer.getvalue())


# ---------------------------------------------------------------------------


BUILDERS = {
    "sop_4412_rev3.pdf": build_sop,
    "inspection_ut_survey_2025.pdf": build_inspection,
    "incident_2019_scan.pdf": build_scanned_incident,
    "pid_cdu1_sheet3.pdf": build_pid,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="data/synthetic/generated_pdf")
    args = parser.parse_args(argv)

    try:
        import reportlab  # noqa: F401
    except ImportError:
        print(
            "reportlab is required to generate the PDF corpus.\n"
            "  pip install -r requirements-dev.txt",
            file=sys.stderr,
        )
        return 1

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    entries = []
    for filename, builder in BUILDERS.items():
        path = out_dir / filename
        builder(path)
        entries.append(
            {
                "filename": filename,
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                "byte_size": path.stat().st_size,
            }
        )
        print(f"  {filename:36} {path.stat().st_size:>8,} bytes")

    manifest = {
        "generator": "data/synthetic/generate_pdfs.py",
        "data_class": "synthetic_test_data",
        "warning": BANNER,
        "note": (
            "Real PDF files with synthetic content. incident_2019_scan.pdf has no text "
            "layer by design and requires OCR. pid_cdu1_sheet3.pdf is vector-dense to "
            "exercise drawing classification; it is not a benchmark for symbol detection."
        ),
        "files": entries,
    }
    (out_dir / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"\nGenerated {len(entries)} PDFs in {out_dir}")
    print("All output is SYNTHETIC TEST DATA in real PDF containers.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
