/**
 * Shared UI primitives.
 *
 * Two rules the whole dashboard depends on:
 *
 * 1. **Every displayed operational value carries a provenance badge.**
 *    `provBadge()` reads the `data_class` the API sent. It is never inferred,
 *    never defaulted to something flattering, and a value that arrives without
 *    one renders as "unlabelled" rather than silently as real.
 *
 * 2. **Loading, empty, error and not-configured are four different states.**
 *    Collapsing them is how a dashboard ends up implying that a blank panel
 *    means "all clear".
 */

// ---------------------------------------------------------------- escaping

/** Escape for text context. All API content passes through here or textContent. */
export function esc(value) {
  if (value === null || value === undefined) return '';
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

export function el(html) {
  const template = document.createElement('template');
  template.innerHTML = html.trim();
  return template.content.firstElementChild;
}

// ------------------------------------------------------------ provenance

const PROV_LABEL = {
  real_source_document: 'Real source',
  synthetic_test_data: 'Synthetic',
  model_derived: 'Model-derived',
  calculated_metric: 'Calculated',
  human_attested: 'Attested',
  reference_taxonomy: 'Taxonomy',
};

const PROV_TITLE = {
  real_source_document: 'Extracted from a real ingested source document.',
  synthetic_test_data:
    'Generated by data/synthetic/generate.py. Test data — not a real plant, not evidence of anything.',
  model_derived: 'Produced by a model inference. Not an audit record.',
  calculated_metric: 'Deterministic computation over stored rows.',
  human_attested: 'Confirmed by a named person. The only audit-grade class.',
  reference_taxonomy: 'Curated reference vocabulary the system was configured with.',
};

/** Provenance badge for a `data_class` value. */
export function provBadge(dataClass) {
  if (!dataClass) {
    return `<span class="prov" style="color:var(--fg-3)" title="The API returned no data_class for this value.">Unlabelled</span>`;
  }
  const label = PROV_LABEL[dataClass] || dataClass;
  const title = PROV_TITLE[dataClass] || '';
  return `<span class="prov ${esc(dataClass)}" title="${esc(title)}">${esc(label)}</span>`;
}

// ---------------------------------------------------------------- states

export function renderLoading(node, message = 'Loading') {
  // role=status so a screen reader hears "loading" instead of silence.
  node.innerHTML = `<div class="state" role="status">
      <span class="spinner" aria-hidden="true"></span> <span class="small">${esc(message)}…</span>
    </div>`;
}

export function renderEmpty(node, { title = 'Nothing here yet', body = '', action = '' } = {}) {
  node.innerHTML = `
    <div class="state" role="status">
      <h3>${esc(title)}</h3>
      ${body ? `<p>${esc(body)}</p>` : ''}
      ${action}
    </div>`;
}

export function renderError(node, error, { title = 'Could not load this panel' } = {}) {
  const detail = error?.detail && Object.keys(error.detail).length
    ? `<pre>${esc(JSON.stringify(error.detail, null, 2))}</pre>`
    : '';
  node.innerHTML = `
    <div class="state error" role="alert">
      <h3>${esc(error?.isOffline ? 'API unreachable' : title)}</h3>
      <p>${esc(error?.message || 'Unknown error')}</p>
      ${error?.code ? `<p class="small dim mono">${esc(error.code)}${error.requestId ? ` · request ${esc(error.requestId)}` : ''}</p>` : ''}
      ${detail}
    </div>`;
}

/**
 * Render a capability the backend reported as unavailable.
 *
 * This is deliberately not an error: it states what is missing and exactly which
 * environment variables would enable it.
 */
export function renderCapability(status, { compact = false } = {}) {
  if (!status) return '';
  const stateBadge = {
    available: '<span class="badge ok">Available</span>',
    disabled: '<span class="badge neutral">Disabled</span>',
    provider_not_configured: '<span class="badge warn">Not configured</span>',
    not_implemented: '<span class="badge info">Not implemented</span>',
    error: '<span class="badge danger">Error</span>',
  }[status.state] || `<span class="badge neutral">${esc(status.state)}</span>`;

  const env = status.required_env?.length
    ? `<code class="env">${status.required_env.map(esc).join('\n')}</code>`
    : '';

  if (compact) {
    return `<div class="row tight small">${stateBadge}<span class="muted">${esc(status.detail || '')}</span></div>`;
  }
  return `
    <div class="capability">
      <h4>${stateBadge} ${esc(status.capability || '')}</h4>
      ${status.detail ? `<p>${esc(status.detail)}</p>` : ''}
      ${env ? `<p class="small muted" style="margin-bottom:4px">Set in <code>.env</code> to enable:</p>${env}` : ''}
    </div>`;
}

// ------------------------------------------------------------ confidence

export function confidenceBand(score) {
  if (score >= 0.75) return 'high';
  if (score >= 0.5) return 'medium';
  return 'low';
}

export function renderConfidence(report) {
  if (!report) return '';
  const band = confidenceBand(report.score);
  const pct = Math.round(report.score * 100);
  const modeBadge = {
    ANSWER: '<span class="badge ok">Answer</span>',
    ANSWER_WITH_CAVEAT: '<span class="badge warn">Answer with caveat</span>',
    ABSTAIN_AND_ROUTE: '<span class="badge danger">Abstained</span>',
    ABSTAIN_NO_ANSWER: '<span class="badge info">Evidence only</span>',
  }[report.mode] || `<span class="badge neutral">${esc(report.mode)}</span>`;

  const signals = Object.entries(report.signals || {})
    .map(([name, value]) => `
      <div class="row tight small" style="justify-content:space-between">
        <span class="muted">${esc(name.replaceAll('_', ' '))}</span>
        <span class="mono tabular">${Number(value).toFixed(2)}</span>
      </div>`)
    .join('');

  return `
    <div class="stack">
      <div class="row">
        ${modeBadge}
        <div class="confidence">
          <div class="confidence-bar" role="meter" aria-valuenow="${pct}" aria-valuemin="0"
               aria-valuemax="100" aria-label="Confidence ${pct} percent, ${band} band">
            <div class="confidence-fill ${band}" style="width:${pct}%"></div>
          </div>
          <span class="mono tabular small" aria-hidden="true">${pct}%</span>
        </div>
      </div>
      <p class="small muted" style="margin:0">${esc(report.explanation || '')}</p>
      <div class="divider" style="margin:4px 0"></div>
      ${signals}
    </div>`;
}

// ---------------------------------------------------------------- format

export function fmtDate(value) {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return esc(value);
  return date.toISOString().slice(0, 10);
}

export function fmtDateTime(value) {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return esc(value);
  return date.toISOString().slice(0, 19).replace('T', ' ') + 'Z';
}

export function fmtNumber(value, digits = 0) {
  if (value === null || value === undefined || value === '') return '—';
  const num = Number(value);
  if (Number.isNaN(num)) return esc(value);
  return num.toLocaleString('en-IN', { minimumFractionDigits: digits, maximumFractionDigits: digits });
}

export function tagChip(tag, { link = true } = {}) {
  if (!tag) return '<span class="dim">—</span>';
  if (!link) return `<span class="tag">${esc(tag)}</span>`;
  // A clickable span is invisible to the keyboard and to assistive tech unless
  // it is given the role and the tab stop explicitly. wireAssetLinks() supplies
  // the Enter/Space handling that a real <a> would get for free.
  return `<span class="tag is-link" role="link" tabindex="0" data-asset="${esc(tag)}"
    aria-label="Open ${esc(tag)} in the knowledge graph">${esc(tag)}</span>`;
}

/**
 * Revision standing of a cited document.
 *
 * The most dangerous thing this system can do is show a technician a procedure
 * from a superseded revision and give them no way to notice. The source viewer
 * has always warned once the document is open; this puts it on the citation row
 * itself, so the warning arrives before the click rather than after it.
 *
 * Silent when the document is current and unversioned — a badge on everything
 * is a badge on nothing.
 */
export function revisionChip({ is_current: isCurrent, revision } = {}) {
  if (isCurrent === false) {
    return `<span class="badge danger no-dot"
      title="This passage comes from a superseded revision. Do not work to it.">superseded${
      revision ? ` rev ${esc(revision)}` : ''}</span>`;
  }
  return revision ? `<span class="badge neutral no-dot">rev ${esc(revision)}</span>` : '';
}

/** Render the doc-type chip. */
export function docTypeChip(type) {
  if (!type) return '';
  return `<span class="badge neutral no-dot">${esc(String(type).replaceAll('_', ' '))}</span>`;
}

// ------------------------------------------------------------------- nav

const NAV = [
  ['index.html', 'Overview'],
  ['ingestion.html', 'Ingestion'],
  ['graph.html', 'Knowledge graph'],
  ['copilot.html', 'Copilot'],
  ['reliability.html', 'Reliability'],
  ['compliance.html', 'Compliance'],
  ['field.html', 'Field'],
  ['impact.html', 'Business impact'],
];

/** Mount the shared header. Also renders the live system-status pill. */
export function mountHeader(current) {
  const header = document.querySelector('[data-app-header]');
  if (!header) return;
  // Keyboard users would otherwise tab through eight nav links on every page.
  if (!document.querySelector('.skip-link')) {
    const skip = el('<a class="skip-link" href="#main">Skip to main content</a>');
    document.body.insertBefore(skip, document.body.firstChild);
  }
  header.innerHTML = `
    <div class="brand">
      <div class="brand-mark">AB</div>
      <div>
        <div class="brand-name">Asset &amp; Operations Brain</div>
        <div class="brand-sub">Industrial knowledge substrate</div>
      </div>
    </div>
    <nav class="app-nav" aria-label="Primary">
      ${NAV.map(([href, label]) =>
        `<a href="${href}"${href === current ? ' aria-current="page"' : ''}>${esc(label)}</a>`).join('')}
    </nav>
    <div class="header-status" data-system-status role="status" aria-live="polite"
         aria-label="System status">
      <span class="badge neutral">Checking…</span>
    </div>`;
}

/** Poll /health and reflect the real state in the header pill. */
export async function mountSystemStatus(api) {
  const node = document.querySelector('[data-system-status]');
  if (!node) return;
  const paint = async () => {
    try {
      const health = await api.health();
      const badge = { ok: 'ok', degraded: 'warn', down: 'danger' }[health.status] || 'neutral';
      const down = Object.entries(health.dependencies || {})
        .filter(([, value]) => value.status && value.status !== 'up')
        .map(([name]) => name);
      node.innerHTML = `
        <a href="index.html#system" class="badge ${badge}" style="text-decoration:none"
           title="${esc(down.length ? `Degraded: ${down.join(', ')}` : 'All backing services reachable')}">
          ${esc(health.status)}${down.length ? ` · ${esc(down.join(','))}` : ''}
        </a>`;
    } catch {
      node.innerHTML = '<span class="badge danger">API unreachable</span>';
    }
  };
  await paint();
  setInterval(paint, 15000);
}

/** Delegate clicks on asset chips to the graph explorer. */
export function wireAssetLinks(root = document) {
  const open = (chip) => {
    window.location.href = `graph.html?asset=${encodeURIComponent(chip.dataset.asset)}`;
  };
  root.addEventListener('click', (event) => {
    const chip = event.target.closest('[data-asset]');
    if (chip) open(chip);
  });
  root.addEventListener('keydown', (event) => {
    if (event.key !== 'Enter' && event.key !== ' ') return;
    const chip = event.target.closest?.('[data-asset][role="link"]');
    if (!chip) return;
    event.preventDefault();   // Space would otherwise scroll the page
    open(chip);
  });
}

export function qs(name, fallback = null) {
  return new URLSearchParams(window.location.search).get(name) ?? fallback;
}
