-- =============================================================================
-- 001_core.sql -- Unified Asset & Operations Brain: relational core.
--
-- Design rules encoded in this schema:
--   * Every row that can appear on a dashboard carries `data_class`, so the UI
--     can always state whether a value came from a real source document,
--     clearly-labelled synthetic test data, a model inference, or a
--     deterministic calculation. Nothing is displayed without that label.
--   * Every asserted fact carries provenance: source document, page, extractor,
--     confidence, and the timestamp of extraction.
--   * Temporal validity (`valid_from` / `valid_to`) sits on anything that a
--     document revision or a Management of Change can invalidate.
--   * Identifiers are content-derived (see services/common/ids.py) so ingestion
--     is idempotent: re-submitting the same bytes is a no-op, not a duplicate.
--
-- Idempotent: safe to run repeatedly.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

-- -----------------------------------------------------------------------------
-- Enumerations
-- -----------------------------------------------------------------------------

DO $$ BEGIN
    CREATE TYPE data_class AS ENUM (
        'real_source_document',   -- extracted verbatim from an ingested real document
        'synthetic_test_data',    -- generated by data/synthetic/generate.py, labelled everywhere
        'model_derived',          -- produced by an LLM/ML inference; never an audit record
        'calculated_metric',      -- deterministic computation over stored rows
        'human_attested'          -- confirmed by a named person; the only audit-grade class
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE document_type AS ENUM (
        'pid', 'isometric', 'datasheet', 'sop', 'work_order', 'inspection_report',
        'incident_report', 'moc', 'hazop', 'permit', 'ncr_capa', 'regulation',
        'manual', 'email', 'unknown'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE job_status AS ENUM ('queued', 'running', 'succeeded', 'failed', 'partial', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE resolution_action AS ENUM ('merge', 'link_sibling', 'needs_review', 'separate');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- -----------------------------------------------------------------------------
-- Migration bookkeeping
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schema_migrations (
    filename     TEXT PRIMARY KEY,
    checksum     TEXT        NOT NULL,
    applied_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- Ingestion jobs -- one durable record per submitted file
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ingestion_jobs (
    job_id            TEXT PRIMARY KEY,
    status            job_status   NOT NULL DEFAULT 'queued',
    source            TEXT         NOT NULL,              -- upload | filesystem | s3 | cmms | sharepoint
    source_system     TEXT,                               -- free-form origin label used for cross-system metrics
    submitted_by      TEXT,
    file_count        INTEGER      NOT NULL DEFAULT 0,
    processed_count   INTEGER      NOT NULL DEFAULT 0,
    failed_count      INTEGER      NOT NULL DEFAULT 0,
    skipped_count     INTEGER      NOT NULL DEFAULT 0,    -- duplicates rejected by content hash
    chunks_created    INTEGER      NOT NULL DEFAULT 0,
    mentions_created  INTEGER      NOT NULL DEFAULT 0,
    entities_created  INTEGER      NOT NULL DEFAULT 0,
    edges_created     INTEGER      NOT NULL DEFAULT 0,
    stage             TEXT,                               -- current pipeline stage, for live progress
    error             TEXT,
    stage_report      JSONB        NOT NULL DEFAULT '{}'::jsonb,  -- per-stage truthful status incl. skipped stages
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    started_at        TIMESTAMPTZ,
    finished_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_jobs_status_created ON ingestion_jobs (status, created_at DESC);

-- -----------------------------------------------------------------------------
-- Documents
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS documents (
    doc_id           TEXT PRIMARY KEY,
    content_hash     TEXT         NOT NULL UNIQUE,   -- SHA-256; the idempotency key
    title            TEXT         NOT NULL,
    doc_type         document_type NOT NULL DEFAULT 'unknown',
    doc_type_confidence  REAL     NOT NULL DEFAULT 0.0,
    doc_type_method  TEXT,                            -- which classifier signal decided it
    data_class       data_class   NOT NULL,
    source_system    TEXT         NOT NULL DEFAULT 'unknown',
    source_path      TEXT,
    original_filename TEXT        NOT NULL,
    mime_type        TEXT,
    byte_size        BIGINT       NOT NULL,
    page_count       INTEGER,
    has_text_layer   BOOLEAN,                        -- false => OCR path required
    revision         TEXT,
    issued_on        DATE,
    revised_on       DATE,
    superseded_by    TEXT REFERENCES documents (doc_id),
    valid_from       DATE,
    valid_to         DATE,
    is_current       BOOLEAN      NOT NULL DEFAULT TRUE,
    licence_note     TEXT,                            -- provenance/licence for real corpus items
    blob_path        TEXT         NOT NULL,
    ingest_job_id    TEXT REFERENCES ingestion_jobs (job_id),
    metadata         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_documents_type      ON documents (doc_type);
CREATE INDEX IF NOT EXISTS idx_documents_source    ON documents (source_system);
CREATE INDEX IF NOT EXISTS idx_documents_current   ON documents (is_current) WHERE is_current;
CREATE INDEX IF NOT EXISTS idx_documents_dataclass ON documents (data_class);

-- -----------------------------------------------------------------------------
-- Chunks -- retrievable passages with layout provenance
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS document_chunks (
    chunk_id      TEXT PRIMARY KEY,
    doc_id        TEXT NOT NULL REFERENCES documents (doc_id) ON DELETE CASCADE,
    ordinal       INTEGER NOT NULL,
    text          TEXT    NOT NULL,
    -- Contextual header prepended before embedding (blueprint 12.4). Stored
    -- separately so the raw passage remains quotable verbatim for citations.
    context_header TEXT,
    section_path  TEXT,
    page_from     INTEGER,
    page_to       INTEGER,
    char_start    INTEGER,
    char_end      INTEGER,
    bbox          JSONB,                    -- [x0,y0,x1,y1] in page coords, for span highlighting
    chunk_kind    TEXT NOT NULL DEFAULT 'prose',  -- prose | step | record | table_row | summary
    token_count   INTEGER NOT NULL DEFAULT 0,
    data_class    data_class NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (doc_id, ordinal)
);

CREATE INDEX IF NOT EXISTS idx_chunks_doc  ON document_chunks (doc_id);
CREATE INDEX IF NOT EXISTS idx_chunks_kind ON document_chunks (chunk_kind);

-- -----------------------------------------------------------------------------
-- Assets -- the canonical entity layer, mirrored into Neo4j
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS assets (
    asset_id         TEXT PRIMARY KEY,
    canonical_tag    TEXT NOT NULL UNIQUE,
    tag_kind         TEXT NOT NULL,             -- equipment | instrument | line | kks | unparsed
    class_code       TEXT,
    class_label      TEXT,
    unit_prefix      TEXT,
    sequence_no      TEXT,
    item_suffix      TEXT,
    description      TEXT,
    functional_location TEXT,
    serial_no        TEXT,
    oem              TEXT,
    model            TEXT,
    service          TEXT,
    criticality      TEXT,
    site             TEXT,
    data_class       data_class NOT NULL,
    first_seen_doc   TEXT REFERENCES documents (doc_id),
    mention_count    INTEGER NOT NULL DEFAULT 0,
    document_count   INTEGER NOT NULL DEFAULT 0,
    source_system_count INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_assets_class ON assets (class_code);
CREATE INDEX IF NOT EXISTS idx_assets_tag_trgm ON assets USING gin (canonical_tag gin_trgm_ops);

-- Alias table: learned and human-confirmed surface forms. This is how the
-- system acquires plant-specific vocabulary as it ingests.
CREATE TABLE IF NOT EXISTS asset_aliases (
    alias_id      BIGSERIAL PRIMARY KEY,
    asset_id      TEXT NOT NULL REFERENCES assets (asset_id) ON DELETE CASCADE,
    surface_form  TEXT NOT NULL,
    normalised    TEXT NOT NULL,
    confirmed_by  TEXT,                       -- NULL => learned, not yet human-confirmed
    confidence    REAL NOT NULL DEFAULT 0.0,
    method        TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (asset_id, normalised)
);

CREATE INDEX IF NOT EXISTS idx_aliases_normalised ON asset_aliases (normalised);

-- -----------------------------------------------------------------------------
-- Mentions -- the observation layer, kept separate from the entity layer so a
-- bad resolution can be undone without re-ingesting.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mentions (
    mention_id     TEXT PRIMARY KEY,
    chunk_id       TEXT NOT NULL REFERENCES document_chunks (chunk_id) ON DELETE CASCADE,
    doc_id         TEXT NOT NULL REFERENCES documents (doc_id) ON DELETE CASCADE,
    surface_form   TEXT NOT NULL,
    normalised     TEXT NOT NULL,
    tag_kind       TEXT NOT NULL,
    char_start     INTEGER NOT NULL,
    char_end       INTEGER NOT NULL,
    page           INTEGER,
    extractor      TEXT NOT NULL,             -- regex | gazetteer | llm | human
    extractor_confidence REAL NOT NULL DEFAULT 0.0,
    resolved_asset_id TEXT REFERENCES assets (asset_id) ON DELETE SET NULL,
    resolution_score  REAL,
    resolution_method TEXT,
    resolution_action resolution_action,
    needs_review   BOOLEAN NOT NULL DEFAULT FALSE,
    data_class     data_class NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mentions_chunk   ON mentions (chunk_id);
CREATE INDEX IF NOT EXISTS idx_mentions_asset   ON mentions (resolved_asset_id);
CREATE INDEX IF NOT EXISTS idx_mentions_review  ON mentions (needs_review) WHERE needs_review;
CREATE INDEX IF NOT EXISTS idx_mentions_norm    ON mentions (normalised);

-- -----------------------------------------------------------------------------
-- Maintenance / HSE / inspection records
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS work_orders (
    wo_id            TEXT PRIMARY KEY,
    doc_id           TEXT REFERENCES documents (doc_id) ON DELETE SET NULL,
    asset_id         TEXT REFERENCES assets (asset_id) ON DELETE SET NULL,
    raw_asset_tag    TEXT,
    functional_location TEXT,
    wo_type          TEXT,                    -- CORRECTIVE | PREVENTIVE | INSPECTION
    status           TEXT,
    priority         TEXT,
    description      TEXT,
    long_text        TEXT,                    -- the field where the truth actually lives
    as_found         TEXT,
    as_left          TEXT,
    coded_failure_mode   TEXT,                -- what the CMMS dropdown says
    extracted_failure_mode TEXT,              -- what the technician's own words say
    failure_mode_agreement BOOLEAN,           -- NULL until both are known
    opened_on        DATE,
    closed_on        DATE,
    downtime_hours   NUMERIC(10, 2),
    cost             NUMERIC(14, 2),
    currency         TEXT DEFAULT 'INR',
    source_system    TEXT NOT NULL DEFAULT 'unknown',
    data_class       data_class NOT NULL,
    metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wo_asset  ON work_orders (asset_id);
CREATE INDEX IF NOT EXISTS idx_wo_opened ON work_orders (opened_on DESC);
CREATE INDEX IF NOT EXISTS idx_wo_type   ON work_orders (wo_type);

CREATE TABLE IF NOT EXISTS incidents (
    incident_id      TEXT PRIMARY KEY,
    doc_id           TEXT REFERENCES documents (doc_id) ON DELETE SET NULL,
    asset_id         TEXT REFERENCES assets (asset_id) ON DELETE SET NULL,
    raw_asset_tag    TEXT,
    title            TEXT,
    occurred_on      DATE,
    severity         TEXT,
    event_type       TEXT,                    -- incident | near_miss
    narrative        TEXT,
    immediate_cause  TEXT,
    root_cause       TEXT,
    investigation_status TEXT,
    source_system    TEXT NOT NULL DEFAULT 'unknown',
    data_class       data_class NOT NULL,
    metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_incidents_asset    ON incidents (asset_id);
CREATE INDEX IF NOT EXISTS idx_incidents_occurred ON incidents (occurred_on DESC);

CREATE TABLE IF NOT EXISTS inspections (
    inspection_id    TEXT PRIMARY KEY,
    doc_id           TEXT REFERENCES documents (doc_id) ON DELETE SET NULL,
    asset_id         TEXT REFERENCES assets (asset_id) ON DELETE SET NULL,
    raw_asset_tag    TEXT,
    cml_id           TEXT,                    -- condition monitoring location
    method           TEXT,                    -- UT | RT | MPI | VT
    inspected_on     DATE,
    thickness_mm     NUMERIC(8, 3),
    min_required_mm  NUMERIC(8, 3),
    inspector        TEXT,
    finding          TEXT,
    source_system    TEXT NOT NULL DEFAULT 'unknown',
    data_class       data_class NOT NULL,
    metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_inspections_asset ON inspections (asset_id, cml_id, inspected_on);

-- -----------------------------------------------------------------------------
-- Regulatory requirements (atomised) -- powers the compliance feature
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS requirements (
    req_id           TEXT PRIMARY KEY,
    source_standard  TEXT NOT NULL,           -- e.g. OISD-STD-105, Factories Act 1948
    clause           TEXT NOT NULL,
    obligation_text  TEXT NOT NULL,
    modality         TEXT NOT NULL,           -- shall | should | may  (legal weight differs)
    applies_to_class TEXT,
    frequency_months INTEGER,
    limit_json       JSONB,                   -- structured quantitative limits
    trigger_text     TEXT,
    testable_by      TEXT,                    -- permit_record_field | procedure_text | graph_state
    effective_from   DATE,
    amended_by       TEXT REFERENCES requirements (req_id),
    -- Provenance is mandatory here: a compliance claim is only as good as the
    -- traceability of the requirement it is checked against.
    text_status      TEXT NOT NULL,           -- verbatim | paraphrase_for_demo
    provenance_note  TEXT NOT NULL,
    data_class       data_class NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_standard, clause, obligation_text)
);

CREATE INDEX IF NOT EXISTS idx_requirements_standard ON requirements (source_standard);
CREATE INDEX IF NOT EXISTS idx_requirements_class    ON requirements (applies_to_class);

-- -----------------------------------------------------------------------------
-- Events -- the timeline that drives the proactive path
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS events (
    event_id      BIGSERIAL PRIMARY KEY,
    event_type    TEXT NOT NULL,             -- graph.changed | work_order.created | document.ingested ...
    asset_id      TEXT REFERENCES assets (asset_id) ON DELETE SET NULL,
    doc_id        TEXT REFERENCES documents (doc_id) ON DELETE SET NULL,
    job_id        TEXT REFERENCES ingestion_jobs (job_id) ON DELETE SET NULL,
    payload       JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_events_type_time ON events (event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_asset     ON events (asset_id, occurred_at DESC);

-- Notifications produced by the proactive engine. `evidence` is mandatory:
-- a push without its evidence is noise, not knowledge transfer.
CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGSERIAL PRIMARY KEY,
    event_id      BIGINT REFERENCES events (event_id) ON DELETE CASCADE,
    asset_id      TEXT REFERENCES assets (asset_id) ON DELETE SET NULL,
    severity      TEXT NOT NULL,
    audience_role TEXT,
    title         TEXT NOT NULL,
    message       TEXT NOT NULL,
    reason        TEXT NOT NULL,
    evidence      JSONB NOT NULL DEFAULT '[]'::jsonb,
    pattern_id    TEXT,
    match_score   REAL,
    data_class    data_class NOT NULL,
    acknowledged_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_asset   ON notifications (asset_id, created_at DESC);

-- -----------------------------------------------------------------------------
-- Answers and citations -- the audit trail. Every machine assertion is logged
-- with what it was based on, so an auditor can separate inference from record.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS query_log (
    query_id       TEXT PRIMARY KEY,
    question       TEXT NOT NULL,
    normalised_question TEXT NOT NULL,
    user_role      TEXT,
    user_site      TEXT,
    work_order_ctx TEXT,
    intent         TEXT,
    intent_confidence REAL,
    entities       JSONB NOT NULL DEFAULT '[]'::jsonb,
    retrieval_stats JSONB NOT NULL DEFAULT '{}'::jsonb,
    answer_text    TEXT,
    confidence_score REAL,
    confidence_mode  TEXT,                   -- ANSWER | ANSWER_WITH_CAVEAT | ABSTAIN_AND_ROUTE | ABSTAIN_NO_GENERATOR
    abstained      BOOLEAN NOT NULL DEFAULT FALSE,
    generator_provider TEXT NOT NULL DEFAULT 'none',
    latency_ms     INTEGER,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_query_log_created ON query_log (created_at DESC);

CREATE TABLE IF NOT EXISTS citations (
    citation_id   BIGSERIAL PRIMARY KEY,
    query_id      TEXT REFERENCES query_log (query_id) ON DELETE CASCADE,
    marker        TEXT NOT NULL,             -- C1, C2, ...
    chunk_id      TEXT REFERENCES document_chunks (chunk_id) ON DELETE SET NULL,
    doc_id        TEXT REFERENCES documents (doc_id) ON DELETE SET NULL,
    page          INTEGER,
    bbox          JSONB,
    quote         TEXT,                      -- verbatim span; validated against the chunk
    quote_verified BOOLEAN NOT NULL DEFAULT FALSE,
    retriever     TEXT,                      -- lexical | dense | graph | fusion
    rank          INTEGER,
    score         REAL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_citations_query ON citations (query_id);

CREATE TABLE IF NOT EXISTS feedback (
    feedback_id   BIGSERIAL PRIMARY KEY,
    query_id      TEXT REFERENCES query_log (query_id) ON DELETE CASCADE,
    notification_id BIGINT REFERENCES notifications (notification_id) ON DELETE CASCADE,
    verdict       TEXT NOT NULL,             -- up | down
    reason        TEXT,                      -- wrong_source | outdated | incomplete | wrong_asset
    note          TEXT,
    submitted_by  TEXT,
    queued_for_review BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT feedback_target CHECK (query_id IS NOT NULL OR notification_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_feedback_created ON feedback (created_at DESC);

-- -----------------------------------------------------------------------------
-- Review queue -- ambiguous resolutions surfaced to a human rather than guessed
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS review_queue (
    review_id     BIGSERIAL PRIMARY KEY,
    kind          TEXT NOT NULL,             -- entity_resolution | extraction_conflict | low_ocr_confidence
    doc_id        TEXT REFERENCES documents (doc_id) ON DELETE CASCADE,
    mention_id    TEXT REFERENCES mentions (mention_id) ON DELETE CASCADE,
    subject       TEXT NOT NULL,
    detail        JSONB NOT NULL DEFAULT '{}'::jsonb,
    confidence    REAL,
    resolved_at   TIMESTAMPTZ,
    resolved_by   TEXT,
    resolution    TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_review_open ON review_queue (kind, created_at DESC)
    WHERE resolved_at IS NULL;
